apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- daemonset.yaml
# - gotk-components.yaml
# - gotk-sync.yaml
# - apps.yaml
# - configmap.yaml

configMapGenerator:
  - name: nginx-additions
    files:
      - application.properties