apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- apps.yaml

patches:
- path: daemonset-patch.yaml
  target:
    kind: DaemonSet
    name: nginx