apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
resources:
- daemonset.yaml
- namespace.yaml

labels:
- includeSelectors: true
  pairs:
    app: nginx

configMapGenerator:
  - name: nginx-vars
    files:
      - application.properties